// Site mapping: Load JSON metadata from LLVM pass to map site_ids to source locations

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

/// Source location information for a site
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SourceLocation {
    pub site_id: u32,
    pub filename: String,
    pub function: String,
    pub line: u32,
    pub column: u32,
    pub event_type: u8,
    #[serde(default)]
    pub ordinal: Option<u32>,
}

impl SourceLocation {
    /// Format as "filename:function:line:column"
    pub fn format(&self) -> String {
        format!("{}:{}:{}:{}", self.filename, self.function, self.line, self.column)
    }

    /// Format as "filename:line" (short form)
    pub fn format_short(&self) -> String {
        format!("{}:{}", self.filename, self.line)
    }
}

/// Site mapping table: site_id -> SourceLocation
pub struct SiteMap {
    map: HashMap<u32, SourceLocation>,
}

impl SiteMap {
    /// Load site map from JSON file generated by LLVM pass
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self> {
        let json_str = fs::read_to_string(path)?;
        let locations: Vec<SourceLocation> = serde_json::from_str(&json_str)?;

        let mut map = HashMap::new();
        for loc in locations {
            map.insert(loc.site_id, loc);
        }

        Ok(SiteMap { map })
    }

    /// Look up source location by site_id
    pub fn get(&self, site_id: u32) -> Option<&SourceLocation> {
        self.map.get(&site_id)
    }

    /// Get the number of sites in the map
    pub fn len(&self) -> usize {
        self.map.len()
    }

    /// Check if the map is empty
    pub fn is_empty(&self) -> bool {
        self.map.is_empty()
    }

    /// Get all locations (for building remapper)
    pub fn locations(&self) -> impl Iterator<Item = &SourceLocation> {
        self.map.values()
    }
}

/// Remaps site_ids from one compilation to another by matching
/// (function, event_type, ordinal) tuples. This allows cross-compilation
/// diff even when site_ids change due to different optimization levels,
/// recompilations, or absence of debug info.
pub struct SiteRemapper {
    /// Maps trace_b site_id -> trace_a site_id
    remap: HashMap<u32, u32>,
}

impl SiteRemapper {
    /// Build a remapper from two site maps.
    /// For each site in map_b, find the matching site in map_a by
    /// (function, event_type, ordinal) and record the site_id mapping.
    pub fn build(map_a: &SiteMap, map_b: &SiteMap) -> Self {
        // Index map_a by (function, event_type, ordinal) -> site_id
        let mut a_index: HashMap<(String, u8, u32), u32> = HashMap::new();
        for loc in map_a.locations() {
            if let Some(ord) = loc.ordinal {
                a_index.insert(
                    (loc.function.clone(), loc.event_type, ord),
                    loc.site_id,
                );
            }
        }

        let mut remap = HashMap::new();
        for loc in map_b.locations() {
            if let Some(ord) = loc.ordinal {
                let key = (loc.function.clone(), loc.event_type, ord);
                if let Some(&a_site_id) = a_index.get(&key) {
                    if a_site_id != loc.site_id {
                        remap.insert(loc.site_id, a_site_id);
                    }
                }
            }
        }

        SiteRemapper { remap }
    }

    /// Translate a site_id from trace B's address space to trace A's.
    /// Returns the original site_id if no mapping exists.
    pub fn translate(&self, site_id: u32) -> u32 {
        self.remap.get(&site_id).copied().unwrap_or(site_id)
    }

    /// Number of site_ids that need remapping
    pub fn num_remapped(&self) -> usize {
        self.remap.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_load_site_map() {
        // Create a temporary JSON file
        let json_content = r#"[
  {
    "site_id": 123,
    "filename": "kernel.cu",
    "function": "test_kernel",
    "line": 42,
    "column": 5,
    "event_type": 1
  },
  {
    "site_id": 456,
    "filename": "kernel.cu",
    "function": "test_kernel",
    "line": 45,
    "column": 9,
    "event_type": 1
  }
]"#;

        let mut temp_file = NamedTempFile::new().unwrap();
        temp_file.write_all(json_content.as_bytes()).unwrap();
        temp_file.flush().unwrap();

        // Load the site map
        let site_map = SiteMap::load(temp_file.path()).unwrap();

        assert_eq!(site_map.len(), 2);

        // Check first site
        let loc1 = site_map.get(123).unwrap();
        assert_eq!(loc1.filename, "kernel.cu");
        assert_eq!(loc1.line, 42);
        assert_eq!(loc1.format_short(), "kernel.cu:42");

        // Check second site
        let loc2 = site_map.get(456).unwrap();
        assert_eq!(loc2.line, 45);

        // Non-existent site
        assert!(site_map.get(999).is_none());
    }

    #[test]
    fn test_source_location_formatting() {
        let loc = SourceLocation {
            site_id: 123,
            filename: "test.cu".to_string(),
            function: "my_kernel".to_string(),
            line: 42,
            column: 10,
            event_type: 1,
            ordinal: Some(0),
        };

        assert_eq!(loc.format(), "test.cu:my_kernel:42:10");
        assert_eq!(loc.format_short(), "test.cu:42");
    }

    #[test]
    fn test_site_remapper() {
        // Simulate two compilations of the same kernel with different site_ids
        let json_a = r#"[
  {"site_id": 100, "filename": "k.cu", "function": "kern", "line": 0, "column": 0, "event_type": 0, "ordinal": 0},
  {"site_id": 200, "filename": "k.cu", "function": "kern", "line": 0, "column": 0, "event_type": 0, "ordinal": 1},
  {"site_id": 300, "filename": "k.cu", "function": "kern", "line": 0, "column": 0, "event_type": 2, "ordinal": 0}
]"#;
        let json_b = r#"[
  {"site_id": 999, "filename": "k.cu", "function": "kern", "line": 0, "column": 0, "event_type": 0, "ordinal": 0},
  {"site_id": 888, "filename": "k.cu", "function": "kern", "line": 0, "column": 0, "event_type": 0, "ordinal": 1},
  {"site_id": 777, "filename": "k.cu", "function": "kern", "line": 0, "column": 0, "event_type": 2, "ordinal": 0}
]"#;

        let mut file_a = NamedTempFile::new().unwrap();
        file_a.write_all(json_a.as_bytes()).unwrap();
        file_a.flush().unwrap();
        let mut file_b = NamedTempFile::new().unwrap();
        file_b.write_all(json_b.as_bytes()).unwrap();
        file_b.flush().unwrap();

        let map_a = SiteMap::load(file_a.path()).unwrap();
        let map_b = SiteMap::load(file_b.path()).unwrap();
        let remapper = SiteRemapper::build(&map_a, &map_b);

        assert_eq!(remapper.num_remapped(), 3);
        assert_eq!(remapper.translate(999), 100);
        assert_eq!(remapper.translate(888), 200);
        assert_eq!(remapper.translate(777), 300);
        // Unknown site_id passes through unchanged
        assert_eq!(remapper.translate(555), 555);
    }

    #[test]
    fn test_backward_compat_no_ordinal() {
        // JSON without ordinal field should still parse (defaults to None)
        let json = r#"[
  {"site_id": 42, "filename": "test.cu", "function": "kern", "line": 10, "column": 5, "event_type": 0}
]"#;
        let mut file = NamedTempFile::new().unwrap();
        file.write_all(json.as_bytes()).unwrap();
        file.flush().unwrap();

        let map = SiteMap::load(file.path()).unwrap();
        let loc = map.get(42).unwrap();
        assert_eq!(loc.ordinal, None);
    }
}
